import { BsCart3 as Cart, BsArrowLeft as Arrow, BsImage as Image } from 'react-icons/bs';
import { MdClose as Close, MdInfoOutline as Info } from 'react-icons/md';
import { ImStarEmpty as Star, ImStarFull as StarFilled, ImStarHalf as StarHalf } from 'react-icons/im';
import { AiOutlineMinus as Minus } from 'react-icons/ai';
import { GoTriangleDown as Triangle } from 'react-icons/go';
import { GiQueenCrown as Crown } from 'react-icons/gi';
import { BiLogOut as Logout } from 'react-icons/bi';

export const CloseIcon = Close;
export const CartIcon = Cart;
export const ImageIcon = Image;
export const MinusIcon = Minus;
export const ArrowIcon = Arrow;
export const InfoIcon = Info;
export const CrownIcon = Crown;
export const LogoutIcon = Logout;
export const TriangleIcon = Triangle;
export const StarIcon = Star;
export const StarFillIcon = StarFilled;
export const StarHalfIcon = StarHalf;
